name_or_path: google/gemma-2b
class_name: AutoModelForCausalLM
tok_name: AutoTokenizer
layers: gemma_last123
edit_modules:
- model.layers.15.mlp.down_proj
- model.layers.16.mlp.down_proj
- model.layers.17.mlp.down_proj
half: False