name_or_path: openai-community/gpt2-medium
class_name: GPT2LMHeadModel
tok_name: GPT2TokenizerFast
layers: gpt2m_last12
edit_modules:
- transformer.h.23.mlp.c_proj
- transformer.h.22.mlp.c_proj
half: False