name_or_path: meta-llama/Meta-Llama-3-8B
class_name: AutoModelForCausalLM
tok_name: AutoTokenizer
layers: llama3_last123
edit_modules:
- model.layers.29.mlp.down_proj
- model.layers.30.mlp.down_proj
- model.layers.31.mlp.down_proj
half: False