name_or_path: meta-llama/Meta-Llama-3-8B
class_name: AutoModelForCausalLM
tok_name: AutoTokenizer
layers: llama3_123
edit_modules:
- model.layers.0.mlp.down_proj
- model.layers.1.mlp.down_proj
- model.layers.2.mlp.down_proj
half: False