name_or_path: mistralai/Mistral-7B-v0.3
class_name: AutoModelForCausalLM
tok_name: AutoTokenizer
layers: mistral_12
edit_modules:
- model.layers.0.mlp.down_proj
- model.layers.1.mlp.down_proj
half: False